#name: selenium test_browserstack.py
#on:
#  push:
#    branches:
#        - master
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout repository
#      uses: actions / checkout @ v3
#    - name: Setup Python
#      uses: actions / setup - python @ v4
#      with:
#        python - version: 3.9  # Replace 'x' with your desired Python version
#
#    - name: Install dependencies
#      run: |
#        python - m pip install - -upgrade pip
#        pip install pytest
#        pip install selenium
##        pip install openpyxl
#        pip install pytest-html
#        pip install Appium-Python-Client
#
#
#
#    - name: execute py script  # run main.py
#      run: |
#            pytest ./Test_cases/Test_browserstack.py --browser chrome
##           pytest ./Test_cases/Test_DD.py --browser chrome
#
#
##    - name: Send Email Report
##      uses: actions / upload - artifact @ v2
##      with:
##         name: Test Report
##         path: ./ Reports / report.html
##
##    - name: Configure Gmail and Send Email
##      env:
##        GMAIL_USERNAME: ${{secrets.GMAIL_USERNAME}}
##        GMAIL_PASSWORD: ${{secrets.GMAIL_PASSWORD}}
##        RECIPIENT_EMAIL: incharakgowda1998 @ gmail.com  # Replace with the recipient's email
##      run: |
##        python Reports / send_email_script.py $GMAIL_USERNAME $GMAIL_PASSWORD $RECIPIENT_EMAIL
#
#
name: selenium test_browserstack.py
on:
  push:
    branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Replace 'x' with your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Pytest on BrowserStack
      run: pytest testcases/test_browserstack.py

    - name: Send email
      uses: actions/upload-artifact@v2
      with:
          server_address: smtp.example.com  # Replace with your email server address
          from: adithya.g@tibilsolutions.com  # Replace with the sender's email address
          to: kiran.sv@tibilsolutions.com  # Replace with the recipient's email address
          username: ${{ secrets.EMAIL_USERNAME }}  # Replace with the name of your secret containing the email service username/API key
          password: ${{ secrets.EMAIL_PASSWORD }}  # Replace with the name of your secret containing the email service password/API key
          subject: Test Report
          body: |
            Hi there,
            Here's the test report for the latest test run.
            Please find the attached report for more details.

          attachments: # Attach the report to the email
            - ./reports/loginpage.html

#
#    - name: Send Email Report
#      uses: actions/upload-artifact@v2
#      with:
#        name: Test Report
#        path: ./reports/report.html
##
#    - name: Configure Gmail and Send Email
#      env:
#        GMAIL_USERNAME: ${{secrets.GMAIL_USERNAME}}
#        GMAIL_PASSWORD: ${{secrets.GMAIL_PASSWORD}}
#        RECIPIENT_EMAIL: kiran.sv@tibisolutions.com  # Replace with the recipient's email
#      run: |
#        python Reports/send_email_script.py $GMAIL_USERNAME $GMAIL_PASSWORD $RECIPIENT_EMAIL
    -
